openapi: 3.0.0
info:
  title: Simple To-Do API
  version: 1.0.0
paths:
  /todos:
    get:
      summary: Get all to-do items
      responses:
        '200':
          description: A list of to-do items
          content:
            application/json:
              example:
                - id: 1
                  title: Buy groceries
                  completed: false
                - id: 2
                  title: Write an API guide
                  completed: true
    post:
      summary: Create a new to-do item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        '201':
          description: The newly created to-do item
          content:
            application/json:
              example:
                id: 3
                title: Finish OpenAPI guide
                completed: false
